import Foundation

/// Kuratierte Basis-Lebensmittel (Grundnahrungsmittel) – sofort & offline durchsuchbar,
/// zweisprachig (Deutsch + Englisch). Schließt die Lücke zu MyFitnessPal: generische
/// Einträge wie „Apfel/Apple", die Open Food Facts (eine Marken-DB) kaum liefert.
/// Nährwerte je 100 g, gerundete Standardwerte (USDA/BLS-nah). Vom Nutzer korrigierbar.
struct LocalFoodDatabase: FoodSearchProvider {

    var sourceName: String { "Basis" }
    var isEnabled: Bool { true }

    /// Ein Basis-Eintrag mit Suchbegriffen (DE + EN + Synonyme) und Nährwerten je 100 g.
    struct Item: Sendable {
        let name: String
        let terms: [String]
        let kcal: Double
        let protein: Double
        let carbs: Double
        let fat: Double
        var fiber: Double? = nil
        var sugar: Double? = nil
    }

    func search(_ query: String) async throws -> [FoodSearchResult] {
        let q = query.folding(options: .diacriticInsensitive, locale: .current)
                     .lowercased().trimmingCharacters(in: .whitespaces)
        guard q.count >= 2 else { return [] }
        return Self.items.compactMap { item -> FoodSearchResult? in
            let hit = item.terms.contains { term in
                let t = term.folding(options: .diacriticInsensitive, locale: .current)
                return t.contains(q) || q.contains(t)
            }
            guard hit else { return nil }
            return FoodSearchResult(
                id: "basis:\(item.name)",
                name: item.name,
                brand: nil,
                barcode: nil,
                source: sourceName,
                kcalPer100g: item.kcal,
                proteinPer100g: item.protein,
                carbsPer100g: item.carbs,
                fatPer100g: item.fat,
                fiberPer100g: item.fiber,
                sugarPer100g: item.sugar,
                sodiumMgPer100g: nil
            )
        }
    }

    // MARK: Datensatz (225 Grundnahrungsmittel, generiert & geprüft)

    static let items: [Item] = [
        Item(name: "Apfel", terms: ["apfel", "apple", "äpfel"], kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, fiber: 2.4, sugar: 10),
        Item(name: "Banane", terms: ["banane", "banana"], kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, sugar: 12),
        Item(name: "Orange", terms: ["orange", "apfelsine"], kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, fiber: 2.4, sugar: 9),
        Item(name: "Mandarine", terms: ["mandarine", "clementine", "tangerine"], kcal: 53, protein: 0.8, carbs: 13, fat: 0.3, fiber: 1.8, sugar: 11),
        Item(name: "Zitrone", terms: ["zitrone", "lemon"], kcal: 29, protein: 1.1, carbs: 9, fat: 0.3, fiber: 2.8, sugar: 2.5),
        Item(name: "Erdbeere", terms: ["erdbeere", "erdbeeren", "strawberry"], kcal: 32, protein: 0.7, carbs: 8, fat: 0.3, fiber: 2, sugar: 5),
        Item(name: "Himbeere", terms: ["himbeere", "raspberry"], kcal: 52, protein: 1.2, carbs: 12, fat: 0.7, fiber: 6.5, sugar: 4.4),
        Item(name: "Blaubeere", terms: ["blaubeere", "heidelbeere", "blueberry"], kcal: 57, protein: 0.7, carbs: 14, fat: 0.3, fiber: 2.4, sugar: 10),
        Item(name: "Weintrauben", terms: ["weintraube", "trauben", "grape", "grapes"], kcal: 69, protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9, sugar: 16),
        Item(name: "Birne", terms: ["birne", "pear"], kcal: 57, protein: 0.4, carbs: 15, fat: 0.1, fiber: 3.1, sugar: 10),
        Item(name: "Pfirsich", terms: ["pfirsich", "peach"], kcal: 39, protein: 0.9, carbs: 10, fat: 0.3, fiber: 1.5, sugar: 8),
        Item(name: "Nektarine", terms: ["nektarine", "nectarine"], kcal: 44, protein: 1.1, carbs: 11, fat: 0.3, fiber: 1.7, sugar: 8),
        Item(name: "Pflaume", terms: ["pflaume", "plum"], kcal: 46, protein: 0.7, carbs: 11, fat: 0.3, fiber: 1.4, sugar: 10),
        Item(name: "Kirsche", terms: ["kirsche", "kirschen", "cherry"], kcal: 63, protein: 1.1, carbs: 16, fat: 0.2, fiber: 2.1, sugar: 13),
        Item(name: "Ananas", terms: ["ananas", "pineapple"], kcal: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4, sugar: 10),
        Item(name: "Mango", terms: ["mango"], kcal: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, sugar: 14),
        Item(name: "Kiwi", terms: ["kiwi"], kcal: 61, protein: 1.1, carbs: 15, fat: 0.5, fiber: 3, sugar: 9),
        Item(name: "Wassermelone", terms: ["wassermelone", "watermelon"], kcal: 30, protein: 0.6, carbs: 8, fat: 0.2, fiber: 0.4, sugar: 6),
        Item(name: "Honigmelone", terms: ["honigmelone", "melone", "melon", "cantaloupe"], kcal: 34, protein: 0.8, carbs: 8, fat: 0.2, fiber: 0.9, sugar: 8),
        Item(name: "Avocado", terms: ["avocado"], kcal: 160, protein: 2, carbs: 9, fat: 15, fiber: 7, sugar: 0.7),
        Item(name: "Grapefruit", terms: ["grapefruit"], kcal: 42, protein: 0.8, carbs: 11, fat: 0.1, fiber: 1.6, sugar: 7),
        Item(name: "Datteln", terms: ["datteln", "dates"], kcal: 282, protein: 2.5, carbs: 75, fat: 0.4, fiber: 8, sugar: 63),
        Item(name: "Feige", terms: ["feige", "fig"], kcal: 74, protein: 0.8, carbs: 19, fat: 0.3, fiber: 2.9, sugar: 16),
        Item(name: "Rosinen", terms: ["rosinen", "raisins"], kcal: 299, protein: 3.1, carbs: 79, fat: 0.5, fiber: 3.7, sugar: 59),
        Item(name: "Granatapfel", terms: ["granatapfel", "pomegranate"], kcal: 83, protein: 1.7, carbs: 19, fat: 1.2, fiber: 4, sugar: 14),
        Item(name: "Tomate", terms: ["tomate", "tomaten", "tomato"], kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sugar: 2.6),
        Item(name: "Gurke", terms: ["gurke", "cucumber"], kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, sugar: 1.7),
        Item(name: "Karotte", terms: ["karotte", "möhre", "carrot"], kcal: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, sugar: 4.7),
        Item(name: "Paprika", terms: ["paprika", "pepper", "bell pepper"], kcal: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, sugar: 4.2),
        Item(name: "Brokkoli", terms: ["brokkoli", "broccoli"], kcal: 34, protein: 2.8, carbs: 7, fat: 0.4, fiber: 2.6, sugar: 1.7),
        Item(name: "Blumenkohl", terms: ["blumenkohl", "cauliflower"], kcal: 25, protein: 1.9, carbs: 5, fat: 0.3, fiber: 2, sugar: 1.9),
        Item(name: "Spinat", terms: ["spinat", "spinach"], kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4),
        Item(name: "Zucchini", terms: ["zucchini", "courgette"], kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, sugar: 2.5),
        Item(name: "Aubergine", terms: ["aubergine", "eggplant"], kcal: 25, protein: 1, carbs: 6, fat: 0.2, fiber: 3, sugar: 3.5),
        Item(name: "Zwiebel", terms: ["zwiebel", "onion"], kcal: 40, protein: 1.1, carbs: 9, fat: 0.1, fiber: 1.7, sugar: 4.2),
        Item(name: "Knoblauch", terms: ["knoblauch", "garlic"], kcal: 149, protein: 6.4, carbs: 33, fat: 0.5, fiber: 2.1, sugar: 1),
        Item(name: "Kartoffel (gekocht)", terms: ["kartoffel", "kartoffeln", "potato"], kcal: 87, protein: 1.9, carbs: 20, fat: 0.1, fiber: 1.8, sugar: 0.9),
        Item(name: "Süßkartoffel", terms: ["süßkartoffel", "sweet potato"], kcal: 86, protein: 1.6, carbs: 20, fat: 0.1, fiber: 3, sugar: 4.2),
        Item(name: "Salat (grün)", terms: ["salat", "kopfsalat", "lettuce"], kcal: 15, protein: 1.4, carbs: 2.9, fat: 0.2, fiber: 1.3, sugar: 0.8),
        Item(name: "Rucola", terms: ["rucola", "arugula", "rocket"], kcal: 25, protein: 2.6, carbs: 3.7, fat: 0.7, fiber: 1.6, sugar: 2),
        Item(name: "Champignons", terms: ["champignon", "champignons", "pilze", "mushroom"], kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, sugar: 2),
        Item(name: "Mais", terms: ["mais", "corn", "maissweet"], kcal: 86, protein: 3.3, carbs: 19, fat: 1.2, fiber: 2.7, sugar: 3.2),
        Item(name: "Erbsen", terms: ["erbsen", "peas"], kcal: 81, protein: 5.4, carbs: 14, fat: 0.4, fiber: 5.7, sugar: 5.7),
        Item(name: "Grüne Bohnen", terms: ["grüne bohnen", "green beans", "brechbohnen"], kcal: 31, protein: 1.8, carbs: 7, fat: 0.1, fiber: 3.4, sugar: 3.3),
        Item(name: "Sellerie", terms: ["sellerie", "celery"], kcal: 16, protein: 0.7, carbs: 3, fat: 0.2, fiber: 1.6, sugar: 1.8),
        Item(name: "Rote Bete", terms: ["rote bete", "beetroot", "rote rübe"], kcal: 43, protein: 1.6, carbs: 10, fat: 0.2, fiber: 2.8, sugar: 7),
        Item(name: "Kürbis", terms: ["kürbis", "pumpkin", "squash"], kcal: 26, protein: 1, carbs: 6.5, fat: 0.1, fiber: 0.5, sugar: 2.8),
        Item(name: "Spargel", terms: ["spargel", "asparagus"], kcal: 20, protein: 2.2, carbs: 3.9, fat: 0.1, fiber: 2.1, sugar: 1.9),
        Item(name: "Kohl/Weißkohl", terms: ["kohl", "weißkohl", "cabbage"], kcal: 25, protein: 1.3, carbs: 6, fat: 0.1, fiber: 2.5, sugar: 3.2),
        Item(name: "Rosenkohl", terms: ["rosenkohl", "brussels sprouts"], kcal: 43, protein: 3.4, carbs: 9, fat: 0.3, fiber: 3.8, sugar: 2.2),
        Item(name: "Lauch", terms: ["lauch", "porree", "leek"], kcal: 61, protein: 1.5, carbs: 14, fat: 0.3, fiber: 1.8, sugar: 3.9),
        Item(name: "Radieschen", terms: ["radieschen", "radish"], kcal: 16, protein: 0.7, carbs: 3.4, fat: 0.1, fiber: 1.6, sugar: 1.9),
        Item(name: "Reis (gekocht)", terms: ["reis", "rice"], kcal: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, sugar: 0.1),
        Item(name: "Vollkornreis (gekocht)", terms: ["vollkornreis", "brown rice"], kcal: 111, protein: 2.6, carbs: 23, fat: 0.9, fiber: 1.8, sugar: 0.4),
        Item(name: "Nudeln (gekocht)", terms: ["nudeln", "pasta", "spaghetti"], kcal: 158, protein: 5.8, carbs: 31, fat: 0.9, fiber: 1.8, sugar: 0.6),
        Item(name: "Vollkornnudeln (gekocht)", terms: ["vollkornnudeln", "whole wheat pasta"], kcal: 149, protein: 6, carbs: 30, fat: 1.5, fiber: 4, sugar: 1),
        Item(name: "Vollkornbrot", terms: ["vollkornbrot", "bread", "wholemeal"], kcal: 247, protein: 9, carbs: 41, fat: 3.4, fiber: 7, sugar: 4),
        Item(name: "Weißbrot / Toast", terms: ["weißbrot", "toast", "white bread"], kcal: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, sugar: 5),
        Item(name: "Brötchen", terms: ["brötchen", "semmel", "roll", "bun"], kcal: 280, protein: 9, carbs: 53, fat: 2.5, fiber: 3, sugar: 2),
        Item(name: "Roggenbrot", terms: ["roggenbrot", "rye bread"], kcal: 259, protein: 8.5, carbs: 48, fat: 3.3, fiber: 6, sugar: 2),
        Item(name: "Knäckebrot", terms: ["knäckebrot", "crispbread"], kcal: 333, protein: 10, carbs: 64, fat: 2.5, fiber: 16, sugar: 1),
        Item(name: "Haferflocken", terms: ["haferflocken", "oats", "oatmeal"], kcal: 372, protein: 13, carbs: 59, fat: 7, fiber: 10, sugar: 1),
        Item(name: "Müsli", terms: ["müsli", "muesli", "granola"], kcal: 360, protein: 9, carbs: 60, fat: 8, fiber: 7, sugar: 15),
        Item(name: "Cornflakes", terms: ["cornflakes", "flakes"], kcal: 357, protein: 7, carbs: 84, fat: 0.9, fiber: 3, sugar: 8),
        Item(name: "Couscous (gekocht)", terms: ["couscous"], kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, fiber: 1.4, sugar: 0.1),
        Item(name: "Quinoa (gekocht)", terms: ["quinoa"], kcal: 120, protein: 4.4, carbs: 21, fat: 1.9, fiber: 2.8, sugar: 0.9),
        Item(name: "Bulgur (gekocht)", terms: ["bulgur"], kcal: 83, protein: 3.1, carbs: 19, fat: 0.2, fiber: 4.5, sugar: 0.1),
        Item(name: "Mehl (Weizen)", terms: ["mehl", "weizenmehl", "flour"], kcal: 364, protein: 10, carbs: 76, fat: 1, fiber: 2.7, sugar: 0.3),
        Item(name: "Brezel", terms: ["brezel", "pretzel", "breze"], kcal: 338, protein: 9, carbs: 71, fat: 3, fiber: 2.5, sugar: 2),
        Item(name: "Reiswaffeln", terms: ["reiswaffel", "rice cake"], kcal: 387, protein: 8, carbs: 82, fat: 2.8, fiber: 4, sugar: 0.3),
        Item(name: "Zwieback", terms: ["zwieback", "rusk"], kcal: 374, protein: 11, carbs: 73, fat: 4, fiber: 3, sugar: 8),
        Item(name: "Polenta (gekocht)", terms: ["polenta"], kcal: 85, protein: 2, carbs: 18, fat: 0.4, fiber: 1, sugar: 0.2),
        Item(name: "Linsen (gekocht)", terms: ["linsen", "lentils"], kcal: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 8, sugar: 1.8),
        Item(name: "Kichererbsen (gekocht)", terms: ["kichererbsen", "chickpeas"], kcal: 164, protein: 9, carbs: 27, fat: 2.6, fiber: 8, sugar: 5),
        Item(name: "Kidneybohnen (gekocht)", terms: ["kidneybohnen", "bohnen", "beans", "kidney beans"], kcal: 127, protein: 9, carbs: 23, fat: 0.5, fiber: 6, sugar: 0.3),
        Item(name: "Schwarze Bohnen (gekocht)", terms: ["schwarze bohnen", "black beans"], kcal: 132, protein: 9, carbs: 24, fat: 0.5, fiber: 9, sugar: 0.3),
        Item(name: "Weiße Bohnen (gekocht)", terms: ["weiße bohnen", "white beans"], kcal: 139, protein: 9, carbs: 25, fat: 0.4, fiber: 6, sugar: 0.3),
        Item(name: "Sojabohnen (gekocht)", terms: ["sojabohnen", "soybeans"], kcal: 173, protein: 17, carbs: 10, fat: 9, fiber: 6, sugar: 3),
        Item(name: "Edamame", terms: ["edamame"], kcal: 121, protein: 12, carbs: 9, fat: 5, fiber: 5, sugar: 2),
        Item(name: "Hummus", terms: ["hummus"], kcal: 166, protein: 8, carbs: 14, fat: 10, fiber: 6, sugar: 0.4),
        Item(name: "Mandeln", terms: ["mandeln", "almonds"], kcal: 579, protein: 21, carbs: 22, fat: 50, fiber: 12, sugar: 4),
        Item(name: "Walnüsse", terms: ["walnüsse", "walnuts"], kcal: 654, protein: 15, carbs: 14, fat: 65, fiber: 7, sugar: 2.6),
        Item(name: "Haselnüsse", terms: ["haselnüsse", "hazelnuts"], kcal: 628, protein: 15, carbs: 17, fat: 61, fiber: 10, sugar: 4),
        Item(name: "Cashewkerne", terms: ["cashew", "cashewkerne", "cashews"], kcal: 553, protein: 18, carbs: 30, fat: 44, fiber: 3.3, sugar: 6),
        Item(name: "Erdnüsse", terms: ["erdnüsse", "peanuts"], kcal: 567, protein: 26, carbs: 16, fat: 49, fiber: 9, sugar: 4),
        Item(name: "Pistazien", terms: ["pistazien", "pistachios"], kcal: 560, protein: 20, carbs: 28, fat: 45, fiber: 10, sugar: 8),
        Item(name: "Sonnenblumenkerne", terms: ["sonnenblumenkerne", "sunflower seeds"], kcal: 584, protein: 21, carbs: 20, fat: 51, fiber: 9, sugar: 2.6),
        Item(name: "Kürbiskerne", terms: ["kürbiskerne", "pumpkin seeds"], kcal: 559, protein: 30, carbs: 11, fat: 49, fiber: 6, sugar: 1.4),
        Item(name: "Chiasamen", terms: ["chiasamen", "chia seeds", "chia"], kcal: 486, protein: 17, carbs: 42, fat: 31, fiber: 34, sugar: 0),
        Item(name: "Leinsamen", terms: ["leinsamen", "flaxseed", "flax"], kcal: 534, protein: 18, carbs: 29, fat: 42, fiber: 27, sugar: 1.5),
        Item(name: "Erdnussbutter", terms: ["erdnussbutter", "peanut butter"], kcal: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, sugar: 9),
        Item(name: "Walnussöl/Nussmus", terms: ["nussmus", "mandelmus", "almond butter"], kcal: 614, protein: 21, carbs: 19, fat: 56, fiber: 10, sugar: 4),
        Item(name: "Hähnchenbrust", terms: ["hähnchen", "hühnchen", "chicken", "hähnchenbrust"], kcal: 165, protein: 31, carbs: 0, fat: 3.6),
        Item(name: "Hähnchenschenkel", terms: ["hähnchenschenkel", "chicken thigh"], kcal: 209, protein: 26, carbs: 0, fat: 11),
        Item(name: "Putenbrust", terms: ["pute", "putenbrust", "turkey"], kcal: 135, protein: 30, carbs: 0, fat: 1),
        Item(name: "Rindfleisch (mager)", terms: ["rind", "rindfleisch", "beef", "steak"], kcal: 217, protein: 26, carbs: 0, fat: 12),
        Item(name: "Hackfleisch (gemischt)", terms: ["hackfleisch", "hack", "mince", "ground beef"], kcal: 250, protein: 18, carbs: 0, fat: 20),
        Item(name: "Schweinefleisch", terms: ["schwein", "schweinefleisch", "pork"], kcal: 242, protein: 27, carbs: 0, fat: 14),
        Item(name: "Schweineschnitzel", terms: ["schnitzel"], kcal: 196, protein: 29, carbs: 0, fat: 8),
        Item(name: "Lammfleisch", terms: ["lamm", "lammfleisch", "lamb"], kcal: 294, protein: 25, carbs: 0, fat: 21),
        Item(name: "Speck/Bacon", terms: ["speck", "bacon"], kcal: 541, protein: 37, carbs: 1.4, fat: 42, sugar: 0),
        Item(name: "Schinken (gekocht)", terms: ["kochschinken", "schinken", "ham"], kcal: 145, protein: 21, carbs: 1, fat: 6, sugar: 1),
        Item(name: "Salami", terms: ["salami"], kcal: 378, protein: 21, carbs: 2, fat: 32, sugar: 1),
        Item(name: "Bratwurst", terms: ["bratwurst"], kcal: 297, protein: 12, carbs: 2, fat: 27, sugar: 1),
        Item(name: "Wiener Würstchen", terms: ["wiener", "würstchen", "frankfurter", "hot dog"], kcal: 290, protein: 12, carbs: 2, fat: 26, sugar: 1),
        Item(name: "Leberwurst", terms: ["leberwurst", "liverwurst"], kcal: 326, protein: 14, carbs: 2, fat: 29, sugar: 0.5),
        Item(name: "Mortadella", terms: ["mortadella"], kcal: 311, protein: 16, carbs: 1, fat: 27, sugar: 0.5),
        Item(name: "Hähnchen paniert/Nuggets", terms: ["nuggets", "chicken nuggets"], kcal: 296, protein: 15, carbs: 16, fat: 18, fiber: 1.5, sugar: 0.5),
        Item(name: "Lachs", terms: ["lachs", "salmon"], kcal: 208, protein: 20, carbs: 0, fat: 13, sugar: 0),
        Item(name: "Thunfisch (Wasser)", terms: ["thunfisch", "tuna"], kcal: 116, protein: 26, carbs: 0, fat: 1, sugar: 0),
        Item(name: "Forelle", terms: ["forelle", "trout"], kcal: 148, protein: 21, carbs: 0, fat: 7, sugar: 0),
        Item(name: "Kabeljau/Dorsch", terms: ["kabeljau", "dorsch", "cod"], kcal: 82, protein: 18, carbs: 0, fat: 0.7, sugar: 0),
        Item(name: "Seelachs/Pollock", terms: ["seelachs", "pollock"], kcal: 92, protein: 19, carbs: 0, fat: 1, sugar: 0),
        Item(name: "Hering", terms: ["hering", "herring"], kcal: 158, protein: 18, carbs: 0, fat: 9, sugar: 0),
        Item(name: "Makrele", terms: ["makrele", "mackerel"], kcal: 205, protein: 19, carbs: 0, fat: 14, sugar: 0),
        Item(name: "Garnelen", terms: ["garnelen", "shrimp", "prawns"], kcal: 99, protein: 24, carbs: 0.2, fat: 0.3, sugar: 0),
        Item(name: "Sardinen", terms: ["sardinen", "sardines"], kcal: 208, protein: 25, carbs: 0, fat: 11, sugar: 0),
        Item(name: "Fischstäbchen", terms: ["fischstäbchen", "fish fingers"], kcal: 200, protein: 12, carbs: 18, fat: 9, fiber: 1, sugar: 1),
        Item(name: "Tintenfisch/Calamari", terms: ["tintenfisch", "calamari", "squid"], kcal: 92, protein: 16, carbs: 3, fat: 1.4, sugar: 0),
        Item(name: "Muscheln", terms: ["muscheln", "mussels"], kcal: 86, protein: 12, carbs: 3.7, fat: 2.2, sugar: 0),
        Item(name: "Ei", terms: ["ei", "eier", "egg", "eggs"], kcal: 155, protein: 13, carbs: 1.1, fat: 11, sugar: 1.1),
        Item(name: "Eiklar", terms: ["eiklar", "eiweiß", "egg white"], kcal: 52, protein: 11, carbs: 0.7, fat: 0.2, sugar: 0.7),
        Item(name: "Rührei", terms: ["rührei", "scrambled eggs"], kcal: 148, protein: 10, carbs: 1.6, fat: 11, sugar: 1.4),
        Item(name: "Milch (3,5%)", terms: ["milch", "vollmilch", "milk"], kcal: 64, protein: 3.4, carbs: 4.8, fat: 3.6, sugar: 4.8),
        Item(name: "Fettarme Milch (1,5%)", terms: ["fettarme milch", "milch 1.5"], kcal: 47, protein: 3.4, carbs: 4.9, fat: 1.5, sugar: 4.9),
        Item(name: "Magermilch", terms: ["magermilch", "skim milk"], kcal: 35, protein: 3.4, carbs: 5, fat: 0.1, sugar: 5),
        Item(name: "Hafermilch", terms: ["hafermilch", "oat milk"], kcal: 45, protein: 0.8, carbs: 7, fat: 1.5, fiber: 0.8, sugar: 4),
        Item(name: "Mandelmilch (ungesüßt)", terms: ["mandelmilch", "almond milk"], kcal: 15, protein: 0.5, carbs: 0.6, fat: 1.1, fiber: 0.3, sugar: 0.1),
        Item(name: "Sojamilch", terms: ["sojamilch", "soy milk"], kcal: 43, protein: 3.3, carbs: 2.6, fat: 1.8, fiber: 0.6, sugar: 2),
        Item(name: "Naturjoghurt", terms: ["joghurt", "yogurt", "yoghurt"], kcal: 61, protein: 3.5, carbs: 4.7, fat: 3.3, sugar: 4.7),
        Item(name: "Griechischer Joghurt", terms: ["griechischer joghurt", "greek yogurt"], kcal: 97, protein: 9, carbs: 4, fat: 5, sugar: 4),
        Item(name: "Skyr", terms: ["skyr"], kcal: 63, protein: 11, carbs: 4, fat: 0.2, sugar: 4),
        Item(name: "Magerquark", terms: ["quark", "magerquark", "quark mager"], kcal: 67, protein: 12, carbs: 4, fat: 0.2, sugar: 4),
        Item(name: "Hüttenkäse", terms: ["hüttenkäse", "cottage cheese", "körniger frischkäse"], kcal: 98, protein: 11, carbs: 3.4, fat: 4.3, sugar: 2.7),
        Item(name: "Frischkäse", terms: ["frischkäse", "cream cheese"], kcal: 253, protein: 6, carbs: 4, fat: 24, sugar: 3),
        Item(name: "Mozzarella", terms: ["mozzarella"], kcal: 280, protein: 22, carbs: 2.2, fat: 17, sugar: 1),
        Item(name: "Gouda", terms: ["gouda"], kcal: 356, protein: 25, carbs: 2.2, fat: 27, sugar: 0),
        Item(name: "Cheddar", terms: ["cheddar"], kcal: 403, protein: 25, carbs: 1.3, fat: 33, sugar: 0.5),
        Item(name: "Emmentaler", terms: ["emmentaler", "swiss cheese"], kcal: 380, protein: 28, carbs: 1, fat: 30, sugar: 0),
        Item(name: "Parmesan", terms: ["parmesan", "parmigiano"], kcal: 431, protein: 38, carbs: 4, fat: 29, sugar: 0.9),
        Item(name: "Feta", terms: ["feta"], kcal: 264, protein: 14, carbs: 4, fat: 21, sugar: 4),
        Item(name: "Camembert/Brie", terms: ["camembert", "brie"], kcal: 300, protein: 20, carbs: 0.5, fat: 24, sugar: 0.5),
        Item(name: "Butter", terms: ["butter"], kcal: 717, protein: 0.9, carbs: 0.1, fat: 81, sugar: 0.1),
        Item(name: "Sahne (30%)", terms: ["sahne", "schlagsahne", "cream"], kcal: 292, protein: 2.1, carbs: 3, fat: 30, sugar: 3),
        Item(name: "Schmand/Sauerrahm", terms: ["schmand", "saure sahne", "sour cream"], kcal: 162, protein: 3, carbs: 3.5, fat: 15, sugar: 3),
        Item(name: "Käse gerieben/Pizzakäse", terms: ["pizzakäse", "reibekäse"], kcal: 356, protein: 25, carbs: 2, fat: 27, sugar: 0),
        Item(name: "Speisequark (20%)", terms: ["speisequark", "quark 20"], kcal: 109, protein: 11, carbs: 3.5, fat: 5.7, sugar: 3.5),
        Item(name: "Olivenöl", terms: ["olivenöl", "olive oil", "öl", "oil"], kcal: 884, protein: 0, carbs: 0, fat: 100, sugar: 0),
        Item(name: "Rapsöl", terms: ["rapsöl", "canola oil"], kcal: 884, protein: 0, carbs: 0, fat: 100, sugar: 0),
        Item(name: "Sonnenblumenöl", terms: ["sonnenblumenöl", "sunflower oil"], kcal: 884, protein: 0, carbs: 0, fat: 100, sugar: 0),
        Item(name: "Kokosöl", terms: ["kokosöl", "coconut oil"], kcal: 892, protein: 0, carbs: 0, fat: 99, sugar: 0),
        Item(name: "Margarine", terms: ["margarine"], kcal: 717, protein: 0.2, carbs: 0.7, fat: 80, sugar: 0.5),
        Item(name: "Mayonnaise", terms: ["mayonnaise", "mayo"], kcal: 680, protein: 1, carbs: 1.3, fat: 75, sugar: 1),
        Item(name: "Schmalz", terms: ["schmalz", "lard"], kcal: 902, protein: 0, carbs: 0, fat: 100, sugar: 0),
        Item(name: "Zucker", terms: ["zucker", "sugar"], kcal: 387, protein: 0, carbs: 100, fat: 0, sugar: 100),
        Item(name: "Honig", terms: ["honig", "honey"], kcal: 304, protein: 0.3, carbs: 82, fat: 0, sugar: 82),
        Item(name: "Marmelade", terms: ["marmelade", "konfitüre", "jam"], kcal: 250, protein: 0.4, carbs: 60, fat: 0.1, fiber: 1, sugar: 48),
        Item(name: "Nuss-Nougat-Creme", terms: ["nutella", "nuss nougat", "hazelnut spread"], kcal: 539, protein: 6, carbs: 57, fat: 31, sugar: 57),
        Item(name: "Schokolade (Vollmilch)", terms: ["schokolade", "vollmilchschokolade", "chocolate"], kcal: 535, protein: 7.6, carbs: 59, fat: 30, sugar: 52),
        Item(name: "Zartbitterschokolade", terms: ["zartbitter", "dunkle schokolade", "dark chocolate"], kcal: 546, protein: 5, carbs: 61, fat: 31, fiber: 7, sugar: 48),
        Item(name: "Gummibärchen", terms: ["gummibärchen", "gummibären", "gummy bears"], kcal: 343, protein: 7, carbs: 77, fat: 0.2, fiber: 0, sugar: 46),
        Item(name: "Kekse", terms: ["kekse", "cookies", "biscuit", "plätzchen"], kcal: 480, protein: 6, carbs: 64, fat: 22, fiber: 2, sugar: 30),
        Item(name: "Kuchen", terms: ["kuchen", "cake"], kcal: 347, protein: 5, carbs: 50, fat: 15, fiber: 1, sugar: 30),
        Item(name: "Donut", terms: ["donut", "doughnut"], kcal: 452, protein: 5, carbs: 51, fat: 25, fiber: 1.5, sugar: 23),
        Item(name: "Croissant", terms: ["croissant"], kcal: 406, protein: 8, carbs: 46, fat: 21, fiber: 2.6, sugar: 11),
        Item(name: "Muffin", terms: ["muffin"], kcal: 377, protein: 5, carbs: 54, fat: 16, fiber: 1.5, sugar: 30),
        Item(name: "Eis (Vanille)", terms: ["eis", "eiscreme", "ice cream"], kcal: 207, protein: 3.5, carbs: 24, fat: 11, fiber: 0.7, sugar: 21),
        Item(name: "Chips", terms: ["chips", "potato chips", "kartoffelchips"], kcal: 536, protein: 7, carbs: 53, fat: 34, fiber: 4.4, sugar: 0.6),
        Item(name: "Salzstangen", terms: ["salzstangen", "pretzel sticks"], kcal: 381, protein: 10, carbs: 79, fat: 3, fiber: 3, sugar: 2),
        Item(name: "Popcorn", terms: ["popcorn"], kcal: 387, protein: 13, carbs: 78, fat: 4, fiber: 15, sugar: 1),
        Item(name: "Müsliriegel", terms: ["müsliriegel", "granola bar", "cereal bar"], kcal: 450, protein: 7, carbs: 65, fat: 17, fiber: 5, sugar: 30),
        Item(name: "Proteinriegel", terms: ["proteinriegel", "protein bar"], kcal: 350, protein: 30, carbs: 35, fat: 9, fiber: 5, sugar: 5),
        Item(name: "Waffeln", terms: ["waffeln", "waffle"], kcal: 291, protein: 7, carbs: 33, fat: 14, fiber: 1, sugar: 8),
        Item(name: "Pudding", terms: ["pudding"], kcal: 110, protein: 3, carbs: 18, fat: 3, fiber: 0, sugar: 16),
        Item(name: "Milchreis", terms: ["milchreis", "rice pudding"], kcal: 130, protein: 3.5, carbs: 22, fat: 3, fiber: 0.3, sugar: 12),
        Item(name: "Pancakes", terms: ["pancakes", "pfannkuchen", "crêpe"], kcal: 227, protein: 6, carbs: 28, fat: 9, fiber: 1, sugar: 7),
        Item(name: "Bagel", terms: ["bagel"], kcal: 250, protein: 10, carbs: 49, fat: 1.5, fiber: 2, sugar: 5),
        Item(name: "Nährhefe/Hefeflocken", terms: ["hefeflocken", "nutritional yeast"], kcal: 325, protein: 50, carbs: 36, fat: 4, fiber: 20, sugar: 0),
        Item(name: "Pommes frites", terms: ["pommes", "fries", "french fries"], kcal: 312, protein: 3.4, carbs: 41, fat: 15, fiber: 3.8, sugar: 0.3),
        Item(name: "Pizza (Margherita)", terms: ["pizza"], kcal: 266, protein: 11, carbs: 33, fat: 10, fiber: 2.3, sugar: 3.6),
        Item(name: "Pizza Salami", terms: ["pizza salami", "pepperoni pizza"], kcal: 298, protein: 13, carbs: 30, fat: 15, fiber: 2.3, sugar: 3.5),
        Item(name: "Hamburger", terms: ["hamburger", "burger"], kcal: 254, protein: 17, carbs: 30, fat: 9, fiber: 1.6, sugar: 5),
        Item(name: "Cheeseburger", terms: ["cheeseburger"], kcal: 303, protein: 15, carbs: 30, fat: 15, fiber: 1.5, sugar: 6),
        Item(name: "Döner Kebab", terms: ["döner", "kebab"], kcal: 215, protein: 15, carbs: 16, fat: 11, fiber: 2, sugar: 2),
        Item(name: "Currywurst", terms: ["currywurst"], kcal: 250, protein: 10, carbs: 9, fat: 20, fiber: 1, sugar: 5),
        Item(name: "Lasagne", terms: ["lasagne", "lasagna"], kcal: 135, protein: 7, carbs: 11, fat: 7, fiber: 1, sugar: 3),
        Item(name: "Spaghetti Bolognese", terms: ["bolognese", "spaghetti bolognese"], kcal: 150, protein: 7, carbs: 18, fat: 5, fiber: 1.5, sugar: 3),
        Item(name: "Sushi (Maki)", terms: ["sushi", "maki"], kcal: 150, protein: 4, carbs: 30, fat: 1, fiber: 1, sugar: 4),
        Item(name: "Pommes mit Ketchup", terms: ["fritten"], kcal: 330, protein: 3.5, carbs: 44, fat: 16, fiber: 3.5, sugar: 3),
        Item(name: "Wrap/Burrito", terms: ["wrap", "burrito"], kcal: 215, protein: 9, carbs: 25, fat: 8, fiber: 2, sugar: 2),
        Item(name: "Gemüsesuppe", terms: ["gemüsesuppe", "vegetable soup", "suppe"], kcal: 40, protein: 1.5, carbs: 6, fat: 1, fiber: 1.2, sugar: 2),
        Item(name: "Tomatensuppe", terms: ["tomatensuppe", "tomato soup"], kcal: 55, protein: 1.5, carbs: 8, fat: 2, fiber: 0.8, sugar: 5),
        Item(name: "Kartoffelpüree", terms: ["kartoffelpüree", "mashed potato"], kcal: 108, protein: 2, carbs: 17, fat: 4, fiber: 1.4, sugar: 1.6),
        Item(name: "Bratkartoffeln", terms: ["bratkartoffeln", "fried potatoes"], kcal: 150, protein: 2.5, carbs: 21, fat: 6.5, fiber: 2, sugar: 1),
        Item(name: "Gnocchi", terms: ["gnocchi"], kcal: 150, protein: 3.5, carbs: 30, fat: 1.5, fiber: 2, sugar: 0.8),
        Item(name: "Falafel", terms: ["falafel"], kcal: 333, protein: 13, carbs: 32, fat: 18, fiber: 5, sugar: 2),
        Item(name: "Ketchup", terms: ["ketchup"], kcal: 112, protein: 1.3, carbs: 26, fat: 0.1, fiber: 0.3, sugar: 22),
        Item(name: "Senf", terms: ["senf", "mustard"], kcal: 66, protein: 4, carbs: 5, fat: 4, fiber: 3, sugar: 3),
        Item(name: "Sojasauce", terms: ["sojasauce", "soy sauce"], kcal: 53, protein: 8, carbs: 5, fat: 0.6, fiber: 0.8, sugar: 0.4),
        Item(name: "Tomatensauce", terms: ["tomatensauce", "passata", "tomato sauce"], kcal: 35, protein: 1.6, carbs: 7, fat: 0.3, fiber: 1.5, sugar: 5),
        Item(name: "Pesto", terms: ["pesto"], kcal: 450, protein: 5, carbs: 6, fat: 46, fiber: 2, sugar: 2),
        Item(name: "Salatdressing", terms: ["dressing", "salatdressing"], kcal: 330, protein: 1, carbs: 8, fat: 33, fiber: 0, sugar: 5),
        Item(name: "Barbecuesauce", terms: ["bbq", "barbecue"], kcal: 172, protein: 1, carbs: 40, fat: 0.6, fiber: 0.8, sugar: 33),
        Item(name: "Apfelmus", terms: ["apfelmus", "applesauce"], kcal: 68, protein: 0.2, carbs: 17, fat: 0.1, fiber: 1.2, sugar: 15),
        Item(name: "Apfelsaft", terms: ["apfelsaft", "apple juice"], kcal: 46, protein: 0.1, carbs: 11, fat: 0.1, fiber: 0.2, sugar: 10),
        Item(name: "Orangensaft", terms: ["orangensaft", "orange juice", "o-saft"], kcal: 45, protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, sugar: 8),
        Item(name: "Cola", terms: ["cola", "coke"], kcal: 42, protein: 0, carbs: 11, fat: 0, fiber: 0, sugar: 11),
        Item(name: "Cola Zero/Light", terms: ["cola zero", "cola light", "diet coke"], kcal: 0.3, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0),
        Item(name: "Limonade", terms: ["limonade", "lemonade", "fanta", "sprite"], kcal: 38, protein: 0, carbs: 9.5, fat: 0, fiber: 0, sugar: 9),
        Item(name: "Eistee", terms: ["eistee", "iced tea"], kcal: 30, protein: 0, carbs: 7.5, fat: 0, fiber: 0, sugar: 7),
        Item(name: "Bier", terms: ["bier", "beer"], kcal: 43, protein: 0.5, carbs: 3.6, fat: 0, fiber: 0, sugar: 0),
        Item(name: "Bier alkoholfrei", terms: ["alkoholfreies bier", "non alcoholic beer"], kcal: 26, protein: 0.4, carbs: 5.5, fat: 0, fiber: 0, sugar: 3),
        Item(name: "Weißwein", terms: ["weißwein", "white wine"], kcal: 82, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0, sugar: 1),
        Item(name: "Rotwein", terms: ["rotwein", "red wine"], kcal: 85, protein: 0.1, carbs: 2.6, fat: 0, fiber: 0, sugar: 0.6),
        Item(name: "Sekt/Prosecco", terms: ["sekt", "prosecco", "champagner", "champagne"], kcal: 80, protein: 0.2, carbs: 1.5, fat: 0, fiber: 0, sugar: 1.5),
        Item(name: "Kaffee (schwarz)", terms: ["kaffee", "coffee", "espresso"], kcal: 2, protein: 0.1, carbs: 0, fat: 0, fiber: 0, sugar: 0),
        Item(name: "Kaffee mit Milch/Latte", terms: ["latte", "milchkaffee", "cappuccino"], kcal: 55, protein: 3, carbs: 5, fat: 2.5, fiber: 0, sugar: 5),
        Item(name: "Tee (ungesüßt)", terms: ["tee", "tea"], kcal: 1, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0),
        Item(name: "Energydrink", terms: ["energydrink", "energy drink", "red bull"], kcal: 45, protein: 0, carbs: 11, fat: 0, fiber: 0, sugar: 11),
        Item(name: "Smoothie", terms: ["smoothie"], kcal: 55, protein: 0.8, carbs: 13, fat: 0.3, fiber: 1.2, sugar: 11),
        Item(name: "Kakao/Trinkschokolade", terms: ["kakao", "trinkschokolade", "hot chocolate"], kcal: 80, protein: 3.5, carbs: 11, fat: 2.5, fiber: 1, sugar: 10),
        Item(name: "Proteinshake (fertig)", terms: ["proteinshake", "protein shake", "eiweißshake"], kcal: 65, protein: 8, carbs: 4, fat: 1.5, fiber: 0.5, sugar: 2),
        Item(name: "Mineralwasser", terms: ["wasser", "mineralwasser", "water"], kcal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0),
        Item(name: "Buttermilch", terms: ["buttermilch", "buttermilk"], kcal: 40, protein: 3.4, carbs: 4.8, fat: 0.5, fiber: 0, sugar: 4.8),
        Item(name: "Kefir", terms: ["kefir"], kcal: 52, protein: 3.3, carbs: 4.5, fat: 2, fiber: 0, sugar: 4),
        // ---- DACH-Klassiker / benannte Gerichte ----
        Item(name: "Bircher Müsli", terms: ["bircher", "birchermüesli", "birchermuesli", "bircher müsli"], kcal: 140, protein: 4, carbs: 24, fat: 3, fiber: 2, sugar: 12),
        Item(name: "Leberkäse", terms: ["leberkäse", "leberkas", "fleischkäse"], kcal: 280, protein: 13, carbs: 1, fat: 25),
        Item(name: "Spätzle (gekocht)", terms: ["spätzle", "spaetzle"], kcal: 150, protein: 5, carbs: 28, fat: 2, fiber: 1.5, sugar: 1),
        Item(name: "Käsespätzle", terms: ["käsespätzle", "kaesespaetzle"], kcal: 215, protein: 9, carbs: 24, fat: 9, fiber: 1.5, sugar: 1),
        Item(name: "Rösti", terms: ["rösti", "roesti"], kcal: 170, protein: 2.5, carbs: 20, fat: 9, fiber: 1.8, sugar: 0.8),
        Item(name: "Maultaschen", terms: ["maultaschen"], kcal: 180, protein: 9, carbs: 20, fat: 7, fiber: 1.5, sugar: 1.5),
        Item(name: "Kaiserschmarrn", terms: ["kaiserschmarrn", "kaiserschmarren"], kcal: 250, protein: 7, carbs: 30, fat: 11, fiber: 1, sugar: 12),
        Item(name: "Gulasch", terms: ["gulasch", "goulash"], kcal: 130, protein: 12, carbs: 4, fat: 7, fiber: 0.5, sugar: 2),
        Item(name: "Käsekuchen", terms: ["käsekuchen", "cheesecake", "quarkkuchen"], kcal: 290, protein: 7, carbs: 30, fat: 16, fiber: 0.5, sugar: 22),
        Item(name: "Apfelstrudel", terms: ["apfelstrudel", "strudel"], kcal: 240, protein: 3, carbs: 33, fat: 11, fiber: 1.5, sugar: 18),
    ]
}
